import { Transaction, SystemStats } from './types';

export const INITIAL_SYSTEM_STATS: SystemStats = {
  totalEvaluated: 14820,
  totalFlagged: 412,
  preventedFraudUsd: 894320.00,
  averageLatencyMs: 24,
  activeInvestigations: 3,
  mttiMinutes: 1.4,
  rocAuc: 0.942,
  riskDistribution: {
    low: 13980,
    medium: 428,
    high: 412,
  },
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_001928',
    userId: 'usr_98123',
    userName: 'Alexander Chen',
    amount: 4200.00,
    currency: 'USD',
    merchant: 'Unrecognized Tech Vendor',
    category: 'Electronics & Computers',
    location: 'Lagos, NG',
    originLocation: 'Accra, GH',
    originCoords: { lat: 5.6037, lng: -0.1870 },
    locationCoords: { lat: 6.5244, lng: 3.3792 },
    travelDistanceKm: 402,
    timeDeltaMinutes: 2.5,
    calculatedKmhSpeed: 9648,
    deviceId: 'dev_new_882',
    timestamp: new Date().toISOString(),
    fraudProbability: 0.94,
    flagged: true,
    status: 'PENDING_REVIEW',
    mobile2FAStatus: 'NONE',
    llmInvestigation: {
      summary: 'High risk anomaly flagged.',
      reasons: [
        'Transaction amount is 7x higher than user normal average ($600.00).',
        'Physical impossible travel detected: active in Accra, GH 2.5 minutes prior, now attempting purchase in Lagos, NG (9,648 km/h).',
        'Unrecognized hardware token (dev_new_882).',
        'MCC Category flagged under elevated risk classification.'
      ],
      recommendedAction: 'FREEZE_ACCOUNT',
      confidenceScore: 0.96,
      modelUsed: 'gemini-2.5-flash',
    },
    riskFactors: {
      amountDeviationRatio: 7.0,
      isNewDevice: true,
      isGeoAnomaly: true,
      velocityScore: 0.85,
      merchantRisk: 0.72,
    },
    shapValues: [
      { feature: 'amount_vs_historical_avg', impact: 0.42, description: '7.0x ratio over 30-day baseline' },
      { feature: 'geo_velocity_anomaly', impact: 0.28, description: 'Impossible travel: Accra to Lagos in 2.5m (Mach 7.8)' },
      { feature: 'device_fingerprint_match', impact: 0.24, description: 'Unseen hardware token dev_new_882' },
      { feature: 'merchant_category_risk', impact: 0.18, description: 'Elevated tech vendor classification' },
      { feature: 'frequency_velocity_24h', impact: -0.06, description: 'Normal account age (412 days)' },
    ],
  },
  {
    id: 'tx_001927',
    userId: 'usr_44102',
    userName: 'Sarah Jenkins',
    amount: 1450.00,
    currency: 'USD',
    merchant: 'CryptoExchange P2P Gateway',
    category: 'Cryptocurrency & Financial',
    location: 'Bucharest, RO',
    originLocation: 'New York, US',
    originCoords: { lat: 40.7128, lng: -74.0060 },
    locationCoords: { lat: 44.4268, lng: 26.1025 },
    travelDistanceKm: 7640,
    timeDeltaMinutes: 35,
    calculatedKmhSpeed: 13097,
    deviceId: 'dev_unknown_441',
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    fraudProbability: 0.89,
    flagged: true,
    status: 'PENDING_REVIEW',
    mobile2FAStatus: 'NONE',
    llmInvestigation: {
      summary: 'Suspicious crypto off-ramp detected from unfamiliar European IP.',
      reasons: [
        "Transaction amount ($1,450.00) exceeds user's 90-day peak ($320.00) by 453%.",
        'Impossible travel velocity: user active in New York, US 35 minutes prior.',
        'High-risk MCC (Crypto P2P) inconsistent with historical travel/grocery pattern.',
        'Device fingerprint mismatch: unauthenticated user-agent.'
      ],
      recommendedAction: 'FREEZE_ACCOUNT',
      confidenceScore: 0.92,
      modelUsed: 'gemini-2.5-flash',
    },
    riskFactors: {
      amountDeviationRatio: 17.05,
      isNewDevice: true,
      isGeoAnomaly: true,
      velocityScore: 0.90,
      merchantRisk: 0.95,
    },
    shapValues: [
      { feature: 'amount_vs_historical_avg', impact: 0.44, description: '17x deviation over $85 baseline' },
      { feature: 'geo_velocity_anomaly', impact: 0.35, description: 'Mach 10.6 impossible jump NY to Bucharest' },
      { feature: 'device_fingerprint_match', impact: 0.20, description: 'Unknown hardware device' },
      { feature: 'merchant_category_risk', impact: 0.25, description: 'High-risk crypto off-ramp gateway' },
    ],
  },
  {
    id: 'tx_001926',
    userId: 'usr_11094',
    userName: 'Marcus Sterling',
    amount: 32.50,
    currency: 'USD',
    merchant: 'Organic Market & Groceries',
    category: 'Groceries & Supermarkets',
    location: 'Zurich, CH',
    originLocation: 'Zurich, CH',
    originCoords: { lat: 47.3769, lng: 8.5417 },
    locationCoords: { lat: 47.3769, lng: 8.5417 },
    travelDistanceKm: 2,
    timeDeltaMinutes: 45,
    calculatedKmhSpeed: 3,
    deviceId: 'dev_iphone_15_pro',
    timestamp: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    fraudProbability: 0.04,
    flagged: false,
    status: 'AUTO_APPROVED',
    mobile2FAStatus: 'NONE',
    riskFactors: {
      amountDeviationRatio: 0.65,
      isNewDevice: false,
      isGeoAnomaly: false,
      velocityScore: 0.04,
      merchantRisk: 0.02,
    },
  },
  {
    id: 'tx_001925',
    userId: 'usr_88201',
    userName: 'Elena Rostova',
    amount: 5200.00,
    currency: 'USD',
    merchant: 'Emirates Luxury Jewelry',
    category: 'Luxury Goods & Jewelry',
    location: 'Dubai, AE',
    originLocation: 'London, UK',
    originCoords: { lat: 51.5074, lng: -0.1278 },
    locationCoords: { lat: 25.2048, lng: 55.2708 },
    travelDistanceKm: 5470,
    timeDeltaMinutes: 12,
    calculatedKmhSpeed: 27350,
    deviceId: 'dev_dubai_wire_88',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    fraudProbability: 0.97,
    flagged: true,
    status: 'FROZEN',
    mobile2FAStatus: 'DENIED_FRAUD',
    llmInvestigation: {
      summary: 'Emergency Card Freeze: Extreme luxury spike with impossible transcontinental velocity.',
      reasons: [
        'Single transaction of $5,200.00 exceeds previous maximum historical amount ($1,200.00).',
        'Physical impossible travel: London to Dubai (5,470 km) within 12 minutes delta.',
        'High-value liquid merchandise with immediate resale value.'
      ],
      recommendedAction: 'FREEZE_ACCOUNT',
      confidenceScore: 0.98,
      modelUsed: 'gemini-2.5-flash',
    },
    riskFactors: {
      amountDeviationRatio: 12.0,
      isNewDevice: true,
      isGeoAnomaly: true,
      velocityScore: 0.98,
      merchantRisk: 0.88,
    },
  },
  {
    id: 'tx_001924',
    userId: 'usr_44102',
    userName: 'Sarah Jenkins',
    amount: 62.00,
    currency: 'USD',
    merchant: 'Uber Rides Inc',
    category: 'Transportation & Travel',
    location: 'New York, US',
    originLocation: 'New York, US',
    originCoords: { lat: 40.7128, lng: -74.0060 },
    locationCoords: { lat: 40.7589, lng: -73.9851 },
    travelDistanceKm: 5,
    timeDeltaMinutes: 20,
    calculatedKmhSpeed: 15,
    deviceId: 'dev_pixel_990',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    fraudProbability: 0.02,
    flagged: false,
    status: 'AUTO_APPROVED',
    mobile2FAStatus: 'NONE',
    riskFactors: {
      amountDeviationRatio: 0.73,
      isNewDevice: false,
      isGeoAnomaly: false,
      velocityScore: 0.02,
      merchantRisk: 0.01,
    },
  }
];
